---
- name: install podman
  become: yes
  package:
    name: podman
    state: latest

- name: add podman to cockpit
  when: ansible_distribution == "Fedora"
  become: yes
  block:
    - name: install cockpit plugin
      package:
        name: cockpit-podman
        state: latest

    - name: start podman socket (for cockpit)
      service:
        name: io.podman.socket
        state: started
        enabled: yes
